global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: givemeticket-backend
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["backend:8080"]

  - job_name: payment-mock
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["payment-mock:8081"]
